apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xc4khzxyu-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:a5519d836dd9481dbe517a85d625fc08feda71f9@sha256:b90123a11c0ae9fc37fa807d0b4c05ad72f4ae66445cbafdac56662c3808e075
          name: container-image
